apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.flaskNamespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.flaskNamespace }}
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.flaskReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.flaskImage.repository }}:{{ .Values.flaskImage.tag }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb-0.mongodb.default.svc.cluster.local:27017"
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.flaskNamespace }}
  name: flaskapp-service
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.flaskNamespace }}
  name: flaskapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: tomer.octopus.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flaskapp-service
            port:
              number: 80

