apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodbName }}
  labels:
    app: {{ .Values.mongodbName }}
spec:
  ports:
    - name: {{ .Values.mongodbName }}
      port: 27017
  clusterIP: None
  selector:
    app: {{ .Values.mongodbName }}

