apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodbName }}
spec:
  serviceName: {{ .Values.mongodbName }}
  replicas: {{ .Values.mongodbReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongodbName }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodbName }}
    spec:
      containers:
        - name: {{ .Values.mongodbName }}
          image: {{ .Values.mongodbImage.repository }}:{{ .Values.mongodbImage.tag }}
          ports:
            - name: {{ .Values.mongodbName }}
              containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mongodbStorageSize }}

